/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "claves_rpc.h"
#include "claves.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
rpc_destroy_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, rpc_destroy, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
rpc_set_value_1(arg_send_values arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_set_value,
		(xdrproc_t) xdr_arg_send_values, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_get_value_1(int arg1, ret_get_value *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_get_value,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_ret_get_value, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_modify_value_1(arg_send_values arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_modify_value,
		(xdrproc_t) xdr_arg_send_values, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_delete_key_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_delete_key,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rpc_exist_1(int arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, rpc_exist,
		(xdrproc_t) xdr_int, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
