/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES_RPC_H_RPCGEN
#define _CLAVES_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Coord {
	int x;
	int y;
};
typedef struct Coord Coord;

struct ret_get_value {
	int status;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	Coord value3;
};
typedef struct ret_get_value ret_get_value;

struct arg_send_values {
	int key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	Coord value3;
};
typedef struct arg_send_values arg_send_values;

#define CLAVESRPC 100456709
// #define CLAVESRPC 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpc_destroy 1
extern  int * rpc_destroy_1(void *, CLIENT *);
extern  int * rpc_destroy_1_svc(void *, struct svc_req *);
#define rpc_set_value 2
extern  int * rpc_set_value_1(arg_send_values *, CLIENT *);
extern  int * rpc_set_value_1_svc(arg_send_values *, struct svc_req *);
#define rpc_get_value 3
extern  ret_get_value * rpc_get_value_1(int *, CLIENT *);
extern  ret_get_value * rpc_get_value_1_svc(int *, struct svc_req *);
#define rpc_modify_value 4
extern  int * rpc_modify_value_1(arg_send_values *, CLIENT *);
extern  int * rpc_modify_value_1_svc(arg_send_values *, struct svc_req *);
#define rpc_delete_key 5
extern  int * rpc_delete_key_1(int *, CLIENT *);
extern  int * rpc_delete_key_1_svc(int *, struct svc_req *);
#define rpc_exist 6
extern  int * rpc_exist_1(int *, CLIENT *);
extern  int * rpc_exist_1_svc(int *, struct svc_req *);
extern int clavesrpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpc_destroy 1
extern  int * rpc_destroy_1();
extern  int * rpc_destroy_1_svc();
#define rpc_set_value 2
extern  int * rpc_set_value_1();
extern  int * rpc_set_value_1_svc();
#define rpc_get_value 3
extern  ret_get_value * rpc_get_value_1();
extern  ret_get_value * rpc_get_value_1_svc();
#define rpc_modify_value 4
extern  int * rpc_modify_value_1();
extern  int * rpc_modify_value_1_svc();
#define rpc_delete_key 5
extern  int * rpc_delete_key_1();
extern  int * rpc_delete_key_1_svc();
#define rpc_exist 6
extern  int * rpc_exist_1();
extern  int * rpc_exist_1_svc();
extern int clavesrpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Coord (XDR *, Coord*);
extern  bool_t xdr_ret_get_value (XDR *, ret_get_value*);
extern  bool_t xdr_arg_send_values (XDR *, arg_send_values*);

#else /* K&R C */
extern bool_t xdr_Coord ();
extern bool_t xdr_ret_get_value ();
extern bool_t xdr_arg_send_values ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES_RPC_H_RPCGEN */
