/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES_RPC_H_RPCGEN
#define _CLAVES_RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "claves.h"

struct arg_send_values {
	int key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	struct Coord value3;
};
typedef struct arg_send_values arg_send_values;

struct ret_get_value {
	int status;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		double *V_value2_val;
	} V_value2;
	struct Coord value3;
};
typedef struct ret_get_value ret_get_value;

#define CLAVESRPC 100456709
#define CLAVESVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpc_destroy 1
extern  enum clnt_stat rpc_destroy_1(int *, CLIENT *);
extern  bool_t rpc_destroy_1_svc(int *, struct svc_req *);
#define rpc_set_value 2
extern  enum clnt_stat rpc_set_value_1(arg_send_values , int *, CLIENT *);
extern  bool_t rpc_set_value_1_svc(arg_send_values , int *, struct svc_req *);
#define rpc_get_value 3
extern  enum clnt_stat rpc_get_value_1(int , ret_get_value *, CLIENT *);
extern  bool_t rpc_get_value_1_svc(int , ret_get_value *, struct svc_req *);
#define rpc_modify_value 4
extern  enum clnt_stat rpc_modify_value_1(arg_send_values , int *, CLIENT *);
extern  bool_t rpc_modify_value_1_svc(arg_send_values , int *, struct svc_req *);
#define rpc_delete_key 5
extern  enum clnt_stat rpc_delete_key_1(int , int *, CLIENT *);
extern  bool_t rpc_delete_key_1_svc(int , int *, struct svc_req *);
#define rpc_exist 6
extern  enum clnt_stat rpc_exist_1(int , int *, CLIENT *);
extern  bool_t rpc_exist_1_svc(int , int *, struct svc_req *);
extern int clavesrpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpc_destroy 1
extern  enum clnt_stat rpc_destroy_1();
extern  bool_t rpc_destroy_1_svc();
#define rpc_set_value 2
extern  enum clnt_stat rpc_set_value_1();
extern  bool_t rpc_set_value_1_svc();
#define rpc_get_value 3
extern  enum clnt_stat rpc_get_value_1();
extern  bool_t rpc_get_value_1_svc();
#define rpc_modify_value 4
extern  enum clnt_stat rpc_modify_value_1();
extern  bool_t rpc_modify_value_1_svc();
#define rpc_delete_key 5
extern  enum clnt_stat rpc_delete_key_1();
extern  bool_t rpc_delete_key_1_svc();
#define rpc_exist 6
extern  enum clnt_stat rpc_exist_1();
extern  bool_t rpc_exist_1_svc();
extern int clavesrpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arg_send_values (XDR *, arg_send_values*);
extern  bool_t xdr_ret_get_value (XDR *, ret_get_value*);

#else /* K&R C */
extern bool_t xdr_arg_send_values ();
extern bool_t xdr_ret_get_value ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES_RPC_H_RPCGEN */
